# Building googletest (gtest)
FROM ubuntu:24.04 AS googletest

RUN apt-get update && apt-get install -y \
   cmake g++ git

WORKDIR /opt

RUN git clone https://github.com/google/googletest.git -b v1.16.0
WORKDIR /opt/googletest
RUN mkdir build
WORKDIR /opt/googletest/build
RUN cmake .. && make && make install
