# Building googletest (gtest)
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
   cmake g++ git

RUN mkdir -p /opt
WORKDIR /opt

RUN git clone https://github.com/google/googletest.git -b v1.16.0
WORKDIR /opt/googletest
RUN mkdir build
WORKDIR /opt/googletest/build
RUN cmake ..
RUN make && make install

